export const xseData = state => state.xseData
export const kdjData = state => state.kdjData
export const fgzqData = state => state.fgzqData
export const subState = state => state.subState
export const userData = state => state.userData
export const menuState = state => state.menuState
export const flagState = state => state.flagState
export const oderTypeState = state => state.oderTypeState
export const msgState = state => state.msgState
export const openModalState = state => state.openModalState
export const siderbarData = state => state.siderbarData
export const siderbarActiveNode = state => state.siderbarActiveNode
export const resultDataForUser = state => state.resultDataForUser
export const resultDataForMsg = state => state.resultDataForMsg
export const resultDataForRebuy = state => state.resultDataForRebuy
export const tokenState = state => state.tokenState
export const logoutState = state => state.logoutState
export const chargeMessagelistData = state => state.chargeMessagelistData
export const callbackMsg = state => state.callbackMsg
export const switchState = state => state.switchState
export const closeModalName = state => state.closeModalName
export const marketJobState = state => state.marketJobState
export const marketJobByParam = state => state.marketJobByParam
export const marketJob = state => state.marketJob
export const saveAsData = state => state.saveAsData
export const renameData = state => state.renameData
export const market = state => state.market
export const marketingSysId = state => state.marketingSysId
export const messageIsShare = state => state.messageIsShare
export const setCenterAlreadyState = state => state.setCenterAlreadyState
export const isSysMarketingjob = state => state.isSysMarketingjob
export const resultDetailData = state => state.resultDetailData
export const filterResultDetailData = state => state.filterResultDetailData
export const pushRecordData = state => state.pushRecordData
export const filterPushRecordData = state => state.filterPushRecordData
export const unsubscribeRecordData = state => state.unsubscribeRecordData
export const filterUnsubscribeRecordData = state => state.filterUnsubscribeRecordData
export const qianniuTaskData = state => state.qianniuTaskData
export const filterQianniuTaskData = state => state.filterQianniuTaskData
export const processData = state => state.processData
export const repeatClickState = state => state.repeatClickState
export const verificationData = state => state.verificationData
export const jurisdictionData = state => state.jurisdictionData
export const attitudeLoss = state => state.attitudeLoss
export const maergeOrderData = state => state.maergeOrderData
export const filterMaergeOrderData = state => state.filterMaergeOrderData
export const calendarDate = state => state.calendarDate
export const filCalendarData = state => state.filCalendarData
export const maergeMessage = state => state.maergeMessage
export const synchronousData = state => state.synchronousData
export const versionUpdate = state => state.versionUpdate
export const marketJson = state => state.marketJson
export const importantMessage = state => state.importantMessage
export const deductionRule = state => state.deductionRule
export const progressData = state => state.progressData
export const payOrderData = state => state.payOrderData
export const serverCenterData = state => state.serverCenterData
